"""
pages/3_strategies.py — AI-generated strategy options with trade-off comparison
"""
import streamlit as st
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
import dummy_data

# ── CSS ───────────────────────────────────────────────────────────────────────
for css_file in ("CSS_File/style.css", "CSS_File/strategies.css"):
    with open(css_file) as f:
        st.markdown(f"<style>{f.read()}</style>", unsafe_allow_html=True)

# ── Page Header ───────────────────────────────────────────────────────────────
st.markdown("""
<h1 class='page-header-title'>AI Strategies</h1>
<p class='page-header-sub'>Multiple options generated by AI with trade-off analysis</p>
""", unsafe_allow_html=True)

# ── Helper: Risk Badge Colours ────────────────────────────────────────────────
def risk_badge_colors(risk: str) -> tuple[str, str]:
    """Return (background, text) colours for a risk label."""
    if "Medium" in risk:
        return "#fef3c7", "#92400e"
    if "High" in risk:
        return "#fee2e2", "#991b1b"
    return "#d0f5e8", "#005c3e"   # Low

# ── Comparison Table ──────────────────────────────────────────────────────────
table_rows = ""
for s in dummy_data.strategies_data:
    bg, fg = risk_badge_colors(s["risk"])
    label  = s["risk"].replace(" Risk", "")
    table_rows += f"""
    <tr>
        <td>{s['title']}</td>
        <td style="color:#008b5b;font-weight:700;">{s['profit_impact']}</td>
        <td>
            <span class="risk-badge"
                  style="background:{bg};color:{fg};">{label}</span>
        </td>
        <td>{s['confidence']}%</td>
    </tr>"""

st.markdown(f"""
<div class="strategy-table">
    <div style="font-weight:700;font-size:15px;color:#0f172a;margin-bottom:16px;">
        Strategy Comparison</div>
    <table>
        <thead>
            <tr>
                <th>Strategy</th>
                <th>Profit Impact</th>
                <th>Risk</th>
                <th>AI Confidence</th>
            </tr>
        </thead>
        <tbody>{table_rows}</tbody>
    </table>
</div>
""", unsafe_allow_html=True)

# ── Strategy Cards ────────────────────────────────────────────────────────────
col_left, col_right = st.columns(2)

for i, s in enumerate(dummy_data.strategies_data):
    bg, fg = risk_badge_colors(s["risk"])

    actions_html = "".join(
        f'<div class="strategy-action-item">'
        f'<div class="strategy-action-dot"></div>{a}</div>'
        for a in s["actions"]
    )

    card = f"""
    <div class="strategy-card">
        <div class="strategy-card-header">
            <div class="strategy-card-left">
                <div class="strategy-card-icon">
                    <svg width="16" height="16" viewBox="0 0 24 24" fill="none"
                         stroke="#008b5b" stroke-width="2.5" stroke-linecap="round"
                         stroke-linejoin="round">
                        <polyline points="20 6 9 17 4 12"/>
                    </svg>
                </div>
                <div>
                    <div class="strategy-card-title">{s['title']}</div>
                    <span class="risk-badge"
                          style="background:{bg};color:{fg};">{s['risk']}</span>
                </div>
            </div>
            <div>
                <div class="strategy-profit">{s['profit_impact']}</div>
                <div class="strategy-profit-label">profit impact</div>
            </div>
        </div>
        <div class="strategy-desc">{s['desc']}</div>
        <div class="strategy-confidence-row">
            <div class="strategy-confidence-label">AI Confidence</div>
            <div class="strategy-confidence-bar">
                <div class="strategy-confidence-fill"
                     style="width:{s['confidence']}%;"></div>
            </div>
            <div class="strategy-confidence-value">{s['confidence']}%</div>
        </div>
        <div class="strategy-actions-title">ACTION STEPS</div>
        {actions_html}
    </div>"""

    if i % 2 == 0:
        with col_left:
            st.markdown(card, unsafe_allow_html=True)
    else:
        with col_right:
            st.markdown(card, unsafe_allow_html=True)

# ── CTA Button ────────────────────────────────────────────────────────────────
st.markdown("<div style='height:24px;'></div>", unsafe_allow_html=True)
_, btn_col, _ = st.columns([1.5, 1, 1.5])
with btn_col:
    if st.button("View Best Recommendation →", use_container_width=True, type="primary"):
        st.switch_page("pages/5_decision.py")
