import streamlit as st
import dummy_data

with open('style.css') as f:
    st.markdown(f'<style>{f.read()}</style>', unsafe_allow_html=True)
with open('strategies.css') as f:
    st.markdown(f'<style>{f.read()}</style>', unsafe_allow_html=True)

st.markdown("<h1 style='font-size:28px;font-weight:700;color:#0f172a;margin-bottom:4px;'>AI Strategies</h1>",
            unsafe_allow_html=True)
st.markdown("<p style='color:#64748b;margin-top:-12px;margin-bottom:24px;'>Multiple options generated by AI with trade-off analysis</p>",
            unsafe_allow_html=True)

# ── Comparison Table ──────────────────────────────────────────
rows = ""
for s in dummy_data.strategies_data:
    if s['risk'] == 'Low Risk':
        badge_bg = "#d0f5e8"; badge_color = "#005c3e"
    elif s['risk'] == 'Medium Risk':
        badge_bg = "#fef3c7"; badge_color = "#92400e"
    else:
        badge_bg = "#fee2e2"; badge_color = "#991b1b"

    rows += f"""
    <tr>
        <td>{s['title']}</td>
        <td style="color:#008b5b;font-weight:700;">{s['profit_impact']}</td>
        <td>
            <span class="risk-badge"
                  style="background:{badge_bg};color:{badge_color};">
                {s['risk'].replace(' Risk','')}
            </span>
        </td>
        <td>{s['confidence']}%</td>
    </tr>"""

st.markdown(f"""
<div class="strategy-table">
    <div style="font-weight:700;font-size:15px;color:#0f172a;margin-bottom:16px;">
        Strategy Comparison</div>
    <table>
        <thead>
            <tr>
                <th>Strategy</th>
                <th>Profit Impact</th>
                <th>Risk</th>
                <th>Confidence</th>
            </tr>
        </thead>
        <tbody>{rows}</tbody>
    </table>
</div>
""", unsafe_allow_html=True)

# ── Strategy Cards ────────────────────────────────────────────
col1, col2 = st.columns(2)

for i, s in enumerate(dummy_data.strategies_data):
    actions_html = "".join(
        f'<div class="strategy-action-item"><div class="strategy-action-dot"></div>{a}</div>'
        for a in s["actions"]
    )

    if 'Medium' in s['risk']:
        rb_bg = "#fef3c7"; rb_color = "#92400e"
    elif 'High' in s['risk']:
        rb_bg = "#fee2e2"; rb_color = "#991b1b"
    else:
        rb_bg = "#d0f5e8"; rb_color = "#005c3e"

    card_html = f"""
    <div class="strategy-card">
        <div class="strategy-card-header">
            <div class="strategy-card-left">
                <div class="strategy-card-icon">
                    <svg width="16" height="16" viewBox="0 0 24 24" fill="none"
                         stroke="#008b5b" stroke-width="2.5" stroke-linecap="round"
                         stroke-linejoin="round">
                        <polyline points="20 6 9 17 4 12"/>
                    </svg>
                </div>
                <div>
                    <div class="strategy-card-title">{s['title']}</div>
                    <span class="risk-badge"
                          style="background:{rb_bg};color:{rb_color};">
                        {s['risk']}
                    </span>
                </div>
            </div>
            <div>
                <div class="strategy-profit">{s['profit_impact']}</div>
                <div class="strategy-profit-label">profit impact</div>
            </div>
        </div>
        <div class="strategy-desc">{s['desc']}</div>
        <div class="strategy-confidence-row">
            <div class="strategy-confidence-label">AI Confidence</div>
            <div class="strategy-confidence-bar">
                <div class="strategy-confidence-fill" style="width:{s['confidence']}%;"></div>
            </div>
            <div class="strategy-confidence-value">{s['confidence']}%</div>
        </div>
        <div class="strategy-actions-title">ACTION STEPS</div>
        {actions_html}
    </div>"""

    if i % 2 == 0:
        with col1:
            st.markdown(card_html, unsafe_allow_html=True)
    else:
        with col2:
            st.markdown(card_html, unsafe_allow_html=True)

st.markdown("<div style='height:24px;'></div>", unsafe_allow_html=True)
col_center = st.columns([1.5, 1, 1.5])
with col_center[1]:
    if st.button("View Best Recommendation →", use_container_width=True, type="primary"):
        st.switch_page("pages/5_Decision.py")

st.markdown("""
<style>
[data-testid="stButton"] button {
    background-color: #008b5b !important;
    border-color: #008b5b !important;
    color: white !important;
    border-radius: 8px !important;
    font-weight: 600 !important;
    padding: 8px 20px !important;
    font-size: 14px !important;
}
[data-testid="stButton"] button:hover {
    background-color: #006e48 !important;
    border-color: #006e48 !important;
}
</style>
""", unsafe_allow_html=True)