import streamlit as st
import dummy_data

with open('style.css') as f:
    st.markdown(f'<style>{f.read()}</style>', unsafe_allow_html=True)
with open('strategies.css') as f:
    st.markdown(f'<style>{f.read()}</style>', unsafe_allow_html=True)

st.markdown("<h1 style='font-size:28px;font-weight:700;color:#0f172a;margin-bottom:4px;'>AI Strategies</h1>",
            unsafe_allow_html=True)
st.markdown("<p style='color:#64748b;margin-top:-12px;margin-bottom:24px;'>Multiple options generated by AI with trade-off analysis</p>",
            unsafe_allow_html=True)

# ── Comparison Table ─────────────────────────────────────────
rows = ""
for s in dummy_data.strategies_data:
    rows += f"""
    <tr>
        <td>{s['title']}</td>
        <td style="color:#16a34a;font-weight:700;">{s['profit_impact']}</td>
        <td><span style="color:{s['risk_color']};font-weight:600;">{s['risk']}</span></td>
        <td>{s['confidence']}%</td>
    </tr>"""

st.markdown(f"""
<div class="strategy-table">
    <div style="font-weight:700;font-size:15px;color:#0f172a;margin-bottom:14px;">
        Strategy Comparison</div>
    <table>
        <thead>
            <tr>
                <th>Strategy</th>
                <th>Profit Impact</th>
                <th>Risk</th>
                <th>Confidence</th>
            </tr>
        </thead>
        <tbody>{rows}</tbody>
    </table>
</div>
""", unsafe_allow_html=True)

# ── Strategy Cards ────────────────────────────────────────────
col1, col2 = st.columns(2)

for i, strategy in enumerate(dummy_data.strategies_data):
    actions_html = "".join(
        f'<div class="strategy-action-item">• {a}</div>'
        for a in strategy["actions"]
    )
    card_html = f"""
    <div class="strategy-card">
        <div class="strategy-card-header">
            <div>
                <div class="strategy-card-title">{strategy['title']}</div>
                <div class="strategy-risk" style="color:{strategy['risk_color']};">
                    {strategy['risk']}</div>
            </div>
            <div>
                <div class="strategy-profit">{strategy['profit_impact']}</div>
                <div class="strategy-profit-label">profit impact</div>
            </div>
        </div>
        <div class="strategy-desc">{strategy['desc']}</div>
        <div class="strategy-confidence-label">AI Confidence</div>
        <div style="display:flex;align-items:center;gap:10px;">
            <div class="strategy-confidence-bar" style="flex:1;">
                <div class="strategy-confidence-fill"
                     style="width:{strategy['confidence']}%;"></div>
            </div>
            <div class="strategy-confidence-value">{strategy['confidence']}%</div>
        </div>
        <div class="strategy-actions-title">ACTION STEPS</div>
        {actions_html}
    </div>"""

    if i % 2 == 0:
        with col1:
            st.markdown(card_html, unsafe_allow_html=True)
            st.markdown("<div style='margin-bottom:16px;'></div>", unsafe_allow_html=True)
    else:
        with col2:
            st.markdown(card_html, unsafe_allow_html=True)
            st.markdown("<div style='margin-bottom:16px;'></div>", unsafe_allow_html=True)

# ── Button to Decision page ───────────────────────────────────
st.markdown("<div style='height:24px;'></div>", unsafe_allow_html=True)
col_center = st.columns([1, 2, 1])
with col_center[1]:
    if st.button("View Best Recommendation →", use_container_width=True, type="primary"):
        st.switch_page("pages/5_Decision.py")